### ISSUE TITLE
ubuntu打包编译

### ISSUE THREAD

**Issue by 2516455367** [yam8511/go-onnxruntime#2]
onnxr 路径 /usr/local/onnxruntime/lib
编译运行出错

libonnxruntime.so.1.18.0: cannot open shared object file: No such file or directory

**Comment by yam8511** [comment]
> onnxr 路径 /usr/local/onnxruntime/lib
> 
> 编译运行出错
> 
> 
> 
> libonnxruntime.so.1.18.0: cannot open shared object file: No such file or directory

請問意思是編譯成功，但運行時出現這個錯誤訊息嗎？
以及您的onnxruntime 包怎麼方的呢？

**Comment by 2516455367** [comment]
> > onnxr 路径 /usr/local/onnxruntime/lib
> > 编译运行出错
> > libonnxruntime.so.1.18.0：无法打开共享对象文件：没有此文件或目录
> 
> 请问我的意思是编辑成功，但运行时出现这个错误信息？ 以及您的onnxruntime 包是怎么回事？

我这样设置就好了 环境问题 -> export LD_LIBRARY_PATH=/usr/local/onnxruntime/lib/:$LD_LIBRARY_PATH  文档中貌似不对

**Comment by 2516455367** [comment]
已解决  export LD_LIBRARY_PATH=/usr/local/onnxruntime/lib/:$LD_LIBRARY_PATH
